const DEFAULT_RUBRIC = [
  { criterion: 'Requirement Understanding', weight: 10, description: 'Did the learner understand and address all stated requirements?' },
  { criterion: 'Class Responsibilities', weight: 15, description: 'Are class responsibilities clear, appropriately scoped, and following SRP?' },
  { criterion: 'Coupling / Cohesion', weight: 15, description: 'Is the design loosely coupled and highly cohesive?' },
  { criterion: 'Encapsulation / Interfaces', weight: 10, description: 'Are abstractions well-defined with proper information hiding?' },
  { criterion: 'Abstraction / Patterns', weight: 10, description: 'Are design patterns used appropriately and justified by requirements?' },
  { criterion: 'Extensibility', weight: 15, description: 'Can the design evolve when requirements change without major rewrites?' },
  { criterion: 'Edge Cases', weight: 10, description: 'Did the learner consider error scenarios, boundaries, and concurrent access?' },
  { criterion: 'Behaviour / Flow', weight: 5, description: 'Is the main flow clear, correct, and complete?' },
  { criterion: 'Explanation Quality', weight: 5, description: 'Is reasoning clear, decisions justified, and trade-offs acknowledged?' },
  { criterion: 'Trade-offs', weight: 5, description: 'Did the learner acknowledge design trade-offs specific to their choices?' },
];

const problems = [
  {
    title: 'Parking Lot System',
    slug: 'parking-lot',
    description: 'Design a Parking Lot system that can manage multiple floors, multiple vehicle types, and real-time spot availability. The system should support entry/exit of vehicles, ticket generation, and fee calculation.',
    difficulty: 'Medium',
    category: 'OOP · Strategy · Factory',
    requirements: [
      'Support multiple parking floors with multiple spots per floor',
      'Handle different vehicle types: Motorcycle, Car, Truck',
      'Assign appropriate spots based on vehicle type',
      'Generate a parking ticket on entry with timestamp',
      'Calculate fee on exit based on duration and vehicle type',
      'Track real-time spot availability per floor and vehicle type',
      'Support entry and exit gates',
    ],
    constraints: [
      'A spot can only hold one vehicle at a time',
      'Vehicles must park in spots matching their type',
      'Fees should be configurable (not hardcoded)',
      'System should work for at least 5 floors and 100 spots per floor',
    ],
    expectedConsiderations: [
      'How do you model the relationship between ParkingLot, Floor, and Spot?',
      'Who is responsible for finding an available spot — ParkingLot, Floor, or a separate allocator?',
      'How do you abstract fee calculation so new pricing rules can be added?',
      'What happens when the lot is full?',
      'How do you handle concurrent entry/exit (at conceptual level)?',
      'Who owns the Ticket — ParkingLot or TicketService?',
    ],
    rubric: DEFAULT_RUBRIC,
    rubricVersion: '1.0',
  },
  {
    title: 'Vending Machine',
    slug: 'vending-machine',
    description: 'Design a Vending Machine that handles product inventory, accepts payments in multiple forms, dispenses products, and returns change. The machine should have distinct operational states.',
    difficulty: 'Medium',
    category: 'OOP · State · Strategy',
    requirements: [
      'Display available products with prices and quantity',
      'Accept coin and cash payments',
      'Allow product selection before or after payment',
      'Dispense the selected product when sufficient payment is made',
      'Return change if overpaid',
      'Handle out-of-stock products gracefully',
      'Support admin operations: refill inventory, collect cash',
    ],
    constraints: [
      'Machine should have explicit states: Idle, ProductSelected, PaymentPending, Dispensing',
      'Invalid state transitions should be rejected',
      'No partial dispensing — either the product is dispensed fully or not at all',
      'Payment must be collected before dispensing',
    ],
    expectedConsiderations: [
      'How do you model the state machine for the vending machine?',
      'Who is responsible for payment processing — the machine or a PaymentProcessor?',
      'How do you handle multiple coin denominations?',
      'What happens if the machine runs out of change?',
      'How would you add a new payment method (card) in the future?',
      'How do you separate product selection from inventory management?',
    ],
    rubric: DEFAULT_RUBRIC,
    rubricVersion: '1.0',
  },
  {
    title: 'Elevator System',
    slug: 'elevator-system',
    description: 'Design an Elevator System for a multi-floor building with multiple elevators. The system should efficiently dispatch elevators to requested floors and manage direction, capacity, and scheduling.',
    difficulty: 'Hard',
    category: 'OOP · Strategy · Observer',
    requirements: [
      'Support a building with multiple floors and multiple elevators',
      'Handle floor requests from both inside and outside the elevator',
      'Dispatch the most suitable elevator to a requested floor',
      'Track elevator state: Idle, Moving Up, Moving Down, Door Open',
      'Respect elevator capacity limits',
      'Support emergency stop functionality',
      'Minimize wait time through a scheduling algorithm',
    ],
    constraints: [
      'An elevator can only move in one direction at a time',
      'Doors cannot open while the elevator is moving',
      'Capacity must be enforced — overloaded elevators should not move',
      'The system should handle at least 20 floors and 4 elevators',
    ],
    expectedConsiderations: [
      'How do you model the difference between an external floor request and an internal cabin request?',
      'Who decides which elevator responds to a floor call — ElevatorController or each Elevator?',
      'How do you abstract the dispatching algorithm so it can be swapped?',
      'What state machine governs each elevator?',
      'How would you handle an elevator being out of service?',
      'How do you prevent starvation for distant floors?',
    ],
    rubric: DEFAULT_RUBRIC,
    rubricVersion: '1.0',
  },
  {
    title: 'Library Management System',
    slug: 'library-management',
    description: 'Design a Library Management System that manages books, members, borrowing, returns, reservations, and fine calculation. The system should handle multiple copies of the same book.',
    difficulty: 'Medium',
    category: 'OOP · Repository · Observer',
    requirements: [
      'Manage a catalog of books with title, author, ISBN, and genre',
      'Support multiple physical copies of the same book',
      'Allow members to borrow and return books',
      'Track due dates and calculate overdue fines',
      'Allow members to reserve a book currently on loan',
      'Notify members when a reserved book becomes available',
      'Support librarian operations: add/remove books, manage members',
    ],
    constraints: [
      'A member can borrow at most 5 books at a time',
      'Borrowing period is 14 days by default',
      'Fine calculation should be configurable',
      'A member with unpaid fines cannot borrow new books',
    ],
    expectedConsiderations: [
      'How do you distinguish between a Book (logical) and a BookCopy (physical)?',
      'Who is responsible for calculating fines — Member, BorrowRecord, or FineService?',
      'How do you implement the reservation and notification flow?',
      'How would you support searching and filtering the catalog?',
      'What happens when a reserved book is not picked up?',
      'How do you design for multiple fine calculation strategies?',
    ],
    rubric: DEFAULT_RUBRIC,
    rubricVersion: '1.0',
  },
  {
    title: 'Movie Ticket Booking System',
    slug: 'movie-ticket-booking',
    description: 'Design a Movie Ticket Booking System that manages movies, theatres, shows, seat selection, booking, and payment. The system should prevent double-booking and support seat locking during checkout.',
    difficulty: 'Hard',
    category: 'OOP · Strategy · Factory',
    requirements: [
      'Manage movies, theatres, and scheduled shows',
      'Support multiple screen types: Standard, IMAX, 3D',
      'Allow users to browse available shows and select seats',
      'Lock selected seats temporarily during checkout (e.g., 10 minutes)',
      'Process payment and confirm booking',
      'Generate a booking confirmation with seat details',
      'Support cancellation and refund policies',
    ],
    constraints: [
      'A seat can only be booked by one user at a time',
      'Seat locks must expire automatically if payment is not completed',
      'Pricing should vary by seat category (regular, premium, recliner)',
      'Cancellation fees should be configurable based on time before show',
    ],
    expectedConsiderations: [
      'How do you prevent two users from booking the same seat simultaneously?',
      'Who is responsible for seat locking — BookingService, Show, or SeatLockManager?',
      'How do you model the difference between a Seat (physical) and a BookedSeat?',
      'How do you abstract payment so multiple payment methods can be added?',
      'How would you design the pricing strategy for different seat categories and show types?',
      'What happens when a seat lock expires mid-checkout?',
    ],
    rubric: DEFAULT_RUBRIC,
    rubricVersion: '1.0',
  },
];

module.exports = problems;
